services:
  app:
    container_name: job-matching-api
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    container_name: job-matching-database
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data1:/var/lib/postgresql/data1
volumes:
  postgres_data1:
